### ISSUE TITLE
write_vars() takes exactly 3 arguments (1 given)

### ISSUE THREAD

**Issue by dvalenzu** [langmead-lab/FORGe#2]
Hi,

First of all, thanks for having the source code of FORGe freely available.

I was trying to run a minimal example based on the instructions in the README.md file.
 The first script gave some errors, but it produced an output anyways; the second script run fine, but the third one,  ./builds.py, gave an error and stopped the execution. 
Below is the output:

The execution looked like this:

> $ ./vcf_to_1ksnp.py --reference ref.fa --vcf variants.vcf  --out variants.1ksnp 
Error! Row:
['1', '10', 'PTV001', 'AAAA', 'CTG,GCC']
Error! Row:
['1', '90', 'PTV002', 'AAAA', 'CTAG,CGTG']
Error! Row:
['1', '379', 'PTV004', 'AAAAA', 'CCCCC']
Error! Row:
['1', '388', 'PTV005', 'AAAAA', 'CCCCC']
Error! Row:
['1', '415', 'PTV006', 'TTTTT', 'ATACAGA']
Found 9 SNPs
0-indexed: 4 / 9
1-indexed: 5 / 9
$ ./rank.py --method popcov --reference ref.fa --vars variants.1ksnp --window-size 100  --output ordered.txt
popcov
$ ./build.py --reference ref.fa --vars variants.1ksnp --window-size 100 --hisat variants.snp --sorted ordered.txt --pct 50
Found 4 / 4 variants
Traceback (most recent call last):
  File "./build.py", line 127, in <module>
    go(args)
  File "./build.py", line 102, in go
    builder.write_hisat(args.hisat)
  File "./build.py", line 27, in write_hisat
    iohelp.write_vars(filename)
TypeError: write_vars() takes exactly 3 arguments (1 given)

**Comment by alshai** [comment]
calling the scripts as executables causes the system to use `/usr/bin/env python`
Your system might be defaulting to Python 3.x as a result. IIRC the forge scripts

**Comment by milkschen** [comment]
Thanks for pointing this out. This is now fixed.

**Comment by dvalenzu** [comment]
Thanks for your quick solution, it works for me now.
